require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({2:[function(require,module,exports){
require("./index.less");var EventEmitter=require("events").EventEmitter,querystring=require("querystring"),xtend=require("xtend"),React=require("react"),Header=require("./components/header"),bus=new EventEmitter,UrlInput=React.createClass({displayName:"UrlInput",render:function(){return React.createElement("div",{className:"url-input"},React.createElement("input",{value:this.props.src,type:"url",ref:"url",placeholder:"Source code url",onChange:this.onChange}),React.createElement("button",{className:"submit",onClick:this.go},"Go!"))},onChange:function(){var e=React.findDOMNode(this.refs.url);bus.emit("setParams",{src:e.value})},go:function(){bus.emit("go")}}),Settings=React.createClass({displayName:"Settings",render:function(){return React.createElement("div",{className:"settings"},React.createElement(Header,{params:this.props.params,setParams:this.setParams}))},setParams:function(e){bus.emit("setParams",e)}}),Entry=React.createClass({displayName:"Entry",getInitialState:function(){var e=require("./parameters");return e.proxy=e.proxy||"http://crossorigin.me/",e.src="https://raw.githubusercontent.com/jcppman/code-player/master/src/app.js",{params:e}},render:function(){return React.createElement("div",{className:"entry"},React.createElement("div",{className:"title"},React.createElement("h1",null,"Code Player"),React.createElement("p",{className:"sub"},"Your codes should ",React.createElement("span",{className:"wrong"},"speak")," sing for themselves")),React.createElement(UrlInput,{src:this.state.params.src}),React.createElement(Settings,{params:this.state.params}),React.createElement("div",{className:"proxy"},"CORS Proxy:",React.createElement("input",{type:"url",ref:"proxy",value:this.state.params.proxy,onChange:this.changeProxy})))},changeProxy:function(){var e=React.findDOMNode(this.refs.proxy);bus.emit("setParams",{proxy:e.value})},componentDidMount:function(){var e=this;bus.on("setParams",function(t){e.setState({params:xtend(e.state.params,t)})}),bus.on("go",function(){var t="/app.html?"+querystring.stringify(e.state.params);window.location=t})}});React.render(React.createElement(Entry,null),document.getElementById("container"));


},{"./components/header":335,"./index.less":341,"./parameters":343,"events":8,"querystring":15,"react":315,"xtend":328}],341:[function(require,module,exports){
!function(){var e=document.getElementsByTagName("head")[0],t=document.createElement("style");t.type="text/css";var r="body{background-color:black;color:white;font-size:24px}.entry{padding:3rem;text-align:center}.entry>*{padding-top:2rem}.entry .title h1{font-size:3rem}.entry .title p.sub{font-size:1.8rem;color:#ccc}.entry .title p.sub .wrong{text-decoration:line-through}.entry .url-input{text-align:center}.entry .url-input *{display:inline-block;font-size:2rem;border-width:0;height:2.4rem;line-height:2.4rem;vertical-align:middle}.entry .url-input input[type=url]{width:69%;border-radius:.6rem 0 0 .6rem;padding:0;text-align:center}.entry .url-input .submit{width:30%;max-width:6rem;border-radius:0 .6rem .6rem 0;padding:0 1rem;background-color:#4ba74b;border-color:#69bc69;color:white}.entry .proxy input{font-size:1rem;margin-left:1rem}";t.styleSheet?t.styleSheet.cssText=r:t.appendChild(document.createTextNode(r)),e.appendChild(t)}();


},{}]},{},[2]);
